### ISSUE TITLE
Things to do in Milestone 1

### ISSUE THREAD

**Issue by tanmayag97** [UBC-MDS/py-sentimentanalyzer#1]
- [x] Pick a topic
- [x]  Confirm with TA/ Florencia
- [x] Software License
- [x] Code of Conduct
- [x] Contributions document
- [x]  Structure of Project
- [x] 3 or  4 functions docstrings
